execute if block ~~1~ oak_log  run fill ~~1~ ~~1~ air destroy
execute if block ~~1~ spruce_log  run fill ~~1~ ~~1~ air destroy
execute if block ~~1~ cherry_log  run fill ~~1~ ~~1~ air destroy
execute if block ~~1~ jungle_log  run fill ~~1~ ~~1~ air destroy
execute if block ~~1~ birch_log  run fill ~~1~ ~~1~ air destroy
execute if block ~~1~ acacia_log  run fill ~~1~ ~~1~ air destroy
execute if block ~~1~ dark_oak_log  run fill ~~1~ ~~1~ air destroy
execute if block ~~1~ mangrove_log  run fill ~~1~ ~~1~ air destroy
execute if block ~~1~ crimson_stem  run fill ~~1~ ~~1~ air destroy
execute if block ~~1~ warped_stem  run fill ~~1~ ~~1~ air destroy

execute if block ~~2~ oak_log  run fill ~~2~ ~~2~ air destroy
execute if block ~~2~ spruce_log  run fill ~~2~ ~~2~ air destroy
execute if block ~~2~ cherry_log  run fill ~~2~ ~~2~ air destroy
execute if block ~~2~ jungle_log  run fill ~~2~ ~~2~ air destroy
execute if block ~~2~ birch_log  run fill ~~2~ ~~2~ air destroy
execute if block ~~2~ acacia_log  run fill ~~2~ ~~2~ air destroy
execute if block ~~2~ dark_oak_log  run fill ~~2~ ~~2~ air destroy
execute if block ~~2~ mangrove_log  run fill ~~2~ ~~2~ air destroy
execute if block ~~2~ crimson_stem  run fill ~~2~ ~~2~ air destroy
execute if block ~~2~ warped_stem  run fill ~~2~ ~~2~ air destroy

execute if block ~~3~ oak_log  run fill ~~3~ ~~3~ air destroy
execute if block ~~3~ spruce_log  run fill ~~3~ ~~3~ air destroy
execute if block ~~3~ cherry_log  run fill ~~3~ ~~3~ air destroy
execute if block ~~3~ jungle_log  run fill ~~3~ ~~3~ air destroy
execute if block ~~3~ birch_log  run fill ~~3~ ~~3~ air destroy
execute if block ~~3~ acacia_log  run fill ~~3~ ~~3~ air destroy
execute if block ~~3~ dark_oak_log  run fill ~~3~ ~~3~ air destroy
execute if block ~~3~ mangrove_log  run fill ~~3~ ~~3~ air destroy
execute if block ~~3~ crimson_stem  run fill ~~3~ ~~3~ air destroy
execute if block ~~3~ warped_stem  run fill ~~3~ ~~3~ air destroy

execute if block ~~4~ oak_log  run fill ~~4~ ~~4~ air destroy
execute if block ~~4~ spruce_log  run fill ~~4~ ~~4~ air destroy
execute if block ~~4~ cherry_log  run fill ~~4~ ~~4~ air destroy
execute if block ~~4~ jungle_log  run fill ~~4~ ~~4~ air destroy
execute if block ~~4~ birch_log  run fill ~~4~ ~~4~ air destroy
execute if block ~~4~ acacia_log  run fill ~~4~ ~~4~ air destroy
execute if block ~~4~ dark_oak_log  run fill ~~4~ ~~4~ air destroy
execute if block ~~4~ mangrove_log  run fill ~~4~ ~~4~ air destroy
execute if block ~~4~ crimson_stem  run fill ~~4~ ~~4~ air destroy
execute if block ~~4~ warped_stem  run fill ~~4~ ~~4~ air destroy

execute if block ~~5~ oak_log  run fill ~~5~ ~~5~ air destroy
execute if block ~~5~ spruce_log  run fill ~~5~ ~~5~ air destroy
execute if block ~~5~ cherry_log  run fill ~~5~ ~~5~ air destroy
execute if block ~~5~ jungle_log  run fill ~~5~ ~~5~ air destroy
execute if block ~~5~ birch_log  run fill ~~5~ ~~5~ air destroy
execute if block ~~5~ acacia_log  run fill ~~5~ ~~5~ air destroy
execute if block ~~5~ dark_oak_log  run fill ~~5~ ~~5~ air destroy
execute if block ~~5~ mangrove_log  run fill ~~5~ ~~5~ air destroy
execute if block ~~5~ crimson_stem  run fill ~~5~ ~~5~ air destroy
execute if block ~~5~ warped_stem  run fill ~~5~ ~~5~ air destroy

execute if block ~~6~ oak_log  run fill ~~6~ ~~6~ air destroy
execute if block ~~6~ spruce_log  run fill ~~6~ ~~6~ air destroy
execute if block ~~6~ cherry_log  run fill ~~6~ ~~6~ air destroy
execute if block ~~6~ jungle_log  run fill ~~6~ ~~6~ air destroy
execute if block ~~6~ birch_log  run fill ~~6~ ~~6~ air destroy
execute if block ~~6~ acacia_log  run fill ~~6~ ~~6~ air destroy
execute if block ~~6~ dark_oak_log  run fill ~~6~ ~~6~ air destroy
execute if block ~~6~ mangrove_log  run fill ~~6~ ~~6~ air destroy
execute if block ~~6~ crimson_stem  run fill ~~6~ ~~6~ air destroy
execute if block ~~6~ warped_stem  run fill ~~6~ ~~6~ air destroy

execute if block ~~7~ oak_log  run fill ~~7~ ~~7~ air destroy
execute if block ~~7~ spruce_log  run fill ~~7~ ~~7~ air destroy
execute if block ~~7~ cherry_log  run fill ~~7~ ~~7~ air destroy
execute if block ~~7~ jungle_log  run fill ~~7~ ~~7~ air destroy
execute if block ~~7~ birch_log  run fill ~~7~ ~~7~ air destroy
execute if block ~~7~ acacia_log  run fill ~~7~ ~~7~ air destroy
execute if block ~~7~ dark_oak_log  run fill ~~7~ ~~7~ air destroy
execute if block ~~7~ mangrove_log  run fill ~~7~ ~~7~ air destroy
execute if block ~~7~ crimson_stem  run fill ~~7~ ~~7~ air destroy
execute if block ~~7~ warped_stem  run fill ~~7~ ~~7~ air destroy

execute if block ~~8~ oak_log  run fill ~~8~ ~~8~ air destroy
execute if block ~~8~ spruce_log  run fill ~~8~ ~~8~ air destroy
execute if block ~~8~ cherry_log  run fill ~~8~ ~~8~ air destroy
execute if block ~~8~ jungle_log  run fill ~~8~ ~~8~ air destroy
execute if block ~~8~ birch_log  run fill ~~8~ ~~8~ air destroy
execute if block ~~8~ acacia_log  run fill ~~8~ ~~8~ air destroy
execute if block ~~8~ dark_oak_log  run fill ~~8~ ~~8~ air destroy
execute if block ~~8~ mangrove_log  run fill ~~8~ ~~8~ air destroy
execute if block ~~8~ crimson_stem  run fill ~~8~ ~~8~ air destroy
execute if block ~~8~ warped_stem  run fill ~~8~ ~~8~ air destroy

execute if block ~~9~ oak_log  run fill ~~9~ ~~9~ air destroy
execute if block ~~9~ spruce_log  run fill ~~9~ ~~9~ air destroy
execute if block ~~9~ cherry_log  run fill ~~9~ ~~9~ air destroy
execute if block ~~9~ jungle_log  run fill ~~9~ ~~9~ air destroy
execute if block ~~9~ birch_log  run fill ~~9~ ~~9~ air destroy
execute if block ~~9~ acacia_log  run fill ~~9~ ~~9~ air destroy
execute if block ~~9~ dark_oak_log  run fill ~~9~ ~~9~ air destroy
execute if block ~~9~ mangrove_log  run fill ~~9~ ~~9~ air destroy
execute if block ~~9~ crimson_stem  run fill ~~9~ ~~9~ air destroy
execute if block ~~9~ warped_stem  run fill ~~9~ ~~9~ air destroy

execute if block ~~10~ oak_log  run fill ~~10~ ~~10~ air destroy
execute if block ~~10~ spruce_log  run fill ~~10~ ~~10~ air destroy
execute if block ~~10~ cherry_log  run fill ~~10~ ~~10~ air destroy
execute if block ~~10~ jungle_log  run fill ~~10~ ~~10~ air destroy
execute if block ~~10~ birch_log  run fill ~~10~ ~~10~ air destroy
execute if block ~~10~ acacia_log  run fill ~~10~ ~~10~ air destroy
execute if block ~~10~ dark_oak_log  run fill ~~10~ ~~10~ air destroy
execute if block ~~10~ mangrove_log  run fill ~~10~ ~~10~ air destroy
execute if block ~~10~ crimson_stem  run fill ~~10~ ~~10~ air destroy
execute if block ~~10~ warped_stem  run fill ~~10~ ~~10~ air destroy

execute if block ~~11~ oak_log  run fill ~~11~ ~~11~ air destroy
execute if block ~~11~ spruce_log  run fill ~~11~ ~~11~ air destroy
execute if block ~~11~ cherry_log  run fill ~~11~ ~~11~ air destroy
execute if block ~~11~ jungle_log  run fill ~~11~ ~~11~ air destroy
execute if block ~~11~ birch_log  run fill ~~11~ ~~11~ air destroy
execute if block ~~11~ acacia_log  run fill ~~11~ ~~11~ air destroy
execute if block ~~11~ dark_oak_log  run fill ~~11~ ~~11~ air destroy
execute if block ~~11~ mangrove_log  run fill ~~11~ ~~11~ air destroy
execute if block ~~11~ crimson_stem  run fill ~~11~ ~~11~ air destroy
execute if block ~~11~ warped_stem  run fill ~~11~ ~~11~ air destroy

execute if block ~~12~ oak_log  run fill ~~11~ ~~12~ air destroy
execute if block ~~12~ spruce_log  run fill ~~12~ ~~12~ air destroy
execute if block ~~12~ cherry_log  run fill ~~12~ ~~12~ air destroy
execute if block ~~12~ jungle_log  run fill ~~12~ ~~12~ air destroy
execute if block ~~12~ birch_log  run fill ~~12~ ~~12~ air destroy
execute if block ~~12~ acacia_log  run fill ~~12~ ~~12~ air destroy
execute if block ~~12~ dark_oak_log  run fill ~~12~ ~~12~ air destroy
execute if block ~~12~ mangrove_log  run fill ~~12~ ~~12~ air destroy
execute if block ~~12~ crimson_stem  run fill ~~12~ ~~12~ air destroy
execute if block ~~12~ warped_stem  run fill ~~12~ ~~12~ air destroy

execute if block ~~13~ oak_log  run fill ~~13~ ~~13~ air destroy
execute if block ~~13~ spruce_log  run fill ~~13~ ~~13~ air destroy
execute if block ~~13~ cherry_log  run fill ~~13~ ~~13~ air destroy
execute if block ~~13~ jungle_log  run fill ~~13~ ~~13~ air destroy
execute if block ~~13~ birch_log  run fill ~~13~ ~~13~ air destroy
execute if block ~~13~ acacia_log  run fill ~~13~ ~~13~ air destroy
execute if block ~~13~ dark_oak_log  run fill ~~13~ ~~13~ air destroy
execute if block ~~13~ mangrove_log  run fill ~~13~ ~~13~ air destroy
execute if block ~~13~ crimson_stem  run fill ~~13~ ~~13~ air destroy
execute if block ~~13~ warped_stem  run fill ~~13~ ~~13~ air destroy

execute if block ~~14~ oak_log  run fill ~~14~ ~~14~ air destroy
execute if block ~~14~ spruce_log  run fill ~~14~ ~~14~ air destroy
execute if block ~~14~ cherry_log  run fill ~~14~ ~~14~ air destroy
execute if block ~~14~ jungle_log  run fill ~~14~ ~~14~ air destroy
execute if block ~~14~ birch_log  run fill ~~14~ ~~14~ air destroy
execute if block ~~14~ acacia_log  run fill ~~14~ ~~14~ air destroy
execute if block ~~14~ dark_oak_log  run fill ~~14~ ~~14~ air destroy
execute if block ~~14~ mangrove_log  run fill ~~14~ ~~14~ air destroy
execute if block ~~14~ crimson_stem  run fill ~~14~ ~~14~ air destroy
execute if block ~~14~ warped_stem  run fill ~~14~ ~~14~ air destroy

execute if block ~~15~ oak_log  run fill ~~15~ ~~15~ air destroy
execute if block ~~15~ spruce_log  run fill ~~15~ ~~15~ air destroy
execute if block ~~15~ cherry_log  run fill ~~15~ ~~15~ air destroy
execute if block ~~15~ jungle_log  run fill ~~15~ ~~15~ air destroy
execute if block ~~15~ birch_log  run fill ~~15~ ~~15~ air destroy
execute if block ~~15~ acacia_log  run fill ~~15~ ~~15~ air destroy
execute if block ~~15~ dark_oak_log  run fill ~~15~ ~~15~ air destroy
execute if block ~~15~ mangrove_log  run fill ~~15~ ~~15~ air destroy
execute if block ~~15~ crimson_stem  run fill ~~15~ ~~15~ air destroy
execute if block ~~15~ warped_stem  run fill ~~15~ ~~15~ air destroy

execute if block ~~16~ oak_log  run fill ~~16~ ~~16~ air destroy
execute if block ~~16~ spruce_log  run fill ~~16~ ~~16~ air destroy
execute if block ~~16~ cherry_log  run fill ~~16~ ~~16~ air destroy
execute if block ~~16~ jungle_log  run fill ~~16~ ~~16~ air destroy
execute if block ~~16~ birch_log  run fill ~~16~ ~~16~ air destroy
execute if block ~~16~ acacia_log  run fill ~~16~ ~~16~ air destroy
execute if block ~~16~ dark_oak_log  run fill ~~16~ ~~16~ air destroy
execute if block ~~16~ mangrove_log  run fill ~~16~ ~~16~ air destroy
execute if block ~~16~ crimson_stem  run fill ~~16~ ~~16~ air destroy
execute if block ~~16~ warped_stem  run fill ~~16~ ~~16~ air destroy

execute if block ~~17~ oak_log  run fill ~~17~ ~~17~ air destroy
execute if block ~~17~ spruce_log  run fill ~~17~ ~~17~ air destroy
execute if block ~~17~ cherry_log  run fill ~~17~ ~~17~ air destroy
execute if block ~~17~ jungle_log  run fill ~~17~ ~~17~ air destroy
execute if block ~~17~ birch_log  run fill ~~17~ ~~17~ air destroy
execute if block ~~17~ acacia_log  run fill ~~17~ ~~17~ air destroy
execute if block ~~17~ dark_oak_log  run fill ~~17~ ~~17~ air destroy
execute if block ~~17~ mangrove_log  run fill ~~17~ ~~17~ air destroy
execute if block ~~17~ crimson_stem  run fill ~~17~ ~~17~ air destroy
execute if block ~~17~ warped_stem  run fill ~~17~ ~~17~ air destroy

execute if block ~~18~ oak_log  run fill ~~18~ ~~18~ air destroy
execute if block ~~18~ spruce_log  run fill ~~18~ ~~18~ air destroy
execute if block ~~18~ cherry_log  run fill ~~18~ ~~18~ air destroy
execute if block ~~18~ jungle_log  run fill ~~18~ ~~18~ air destroy
execute if block ~~18~ birch_log  run fill ~~18~ ~~18~ air destroy
execute if block ~~18~ acacia_log  run fill ~~18~ ~~18~ air destroy
execute if block ~~18~ dark_oak_log  run fill ~~18~ ~~18~ air destroy
execute if block ~~18~ mangrove_log  run fill ~~18~ ~~18~ air destroy
execute if block ~~18~ crimson_stem  run fill ~~18~ ~~18~ air destroy
execute if block ~~18~ warped_stem  run fill ~~18~ ~~18~ air destroy

execute if block ~~19~ oak_log  run fill ~~19~ ~~19~ air destroy
execute if block ~~19~ spruce_log  run fill ~~19~ ~~19~ air destroy
execute if block ~~19~ cherry_log  run fill ~~19~ ~~19~ air destroy
execute if block ~~19~ jungle_log  run fill ~~19~ ~~19~ air destroy
execute if block ~~19~ birch_log  run fill ~~19~ ~~19~ air destroy
execute if block ~~19~ acacia_log  run fill ~~19~ ~~19~ air destroy
execute if block ~~19~ dark_oak_log  run fill ~~19~ ~~19~ air destroy
execute if block ~~19~ mangrove_log  run fill ~~19~ ~~19~ air destroy
execute if block ~~19~ crimson_stem  run fill ~~19~ ~~19~ air destroy
execute if block ~~19~ warped_stem  run fill ~~19~ ~~19~ air destroy

execute if block ~~20~ oak_log  run fill ~~20~ ~~20~ air destroy
execute if block ~~20~ spruce_log  run fill ~~20~ ~~20~ air destroy
execute if block ~~20~ cherry_log  run fill ~~20~ ~~20~ air destroy
execute if block ~~20~ jungle_log  run fill ~~20~ ~~20~ air destroy
execute if block ~~20~ birch_log  run fill ~~20~ ~~20~ air destroy
execute if block ~~20~ acacia_log  run fill ~~20~ ~~20~ air destroy
execute if block ~~20~ dark_oak_log  run fill ~~20~ ~~20~ air destroy
execute if block ~~20~ mangrove_log  run fill ~~20~ ~~20~ air destroy
execute if block ~~20~ crimson_stem  run fill ~~20~ ~~20~ air destroy
execute if block ~~20~ warped_stem  run fill ~~20~ ~~20~ air destroy

execute if block ~~21~ oak_log  run fill ~~21~ ~~21~ air destroy
execute if block ~~21~ spruce_log  run fill ~~21~ ~~21~ air destroy
execute if block ~~21~ cherry_log  run fill ~~21~ ~~21~ air destroy
execute if block ~~21~ jungle_log  run fill ~~21~ ~~21~ air destroy
execute if block ~~21~ birch_log  run fill ~~21~ ~~21~ air destroy
execute if block ~~21~ acacia_log  run fill ~~21~ ~~21~ air destroy
execute if block ~~21~ dark_oak_log  run fill ~~21~ ~~21~ air destroy
execute if block ~~21~ mangrove_log  run fill ~~21~ ~~21~ air destroy
execute if block ~~21~ crimson_stem  run fill ~~21~ ~~21~ air destroy
execute if block ~~21~ warped_stem  run fill ~~21~ ~~21~ air destroy

execute if block ~~22~ oak_log  run fill ~~22~ ~~22~ air destroy
execute if block ~~22~ spruce_log  run fill ~~22~ ~~22~ air destroy
execute if block ~~22~ cherry_log  run fill ~~22~ ~~22~ air destroy
execute if block ~~22~ jungle_log  run fill ~~22~ ~~22~ air destroy
execute if block ~~22~ birch_log  run fill ~~22~ ~~22~ air destroy
execute if block ~~22~ acacia_log  run fill ~~22~ ~~22~ air destroy
execute if block ~~22~ dark_oak_log  run fill ~~22~ ~~22~ air destroy
execute if block ~~22~ mangrove_log  run fill ~~22~ ~~22~ air destroy
execute if block ~~22~ crimson_stem  run fill ~~22~ ~~22~ air destroy
execute if block ~~22~ warped_stem  run fill ~~22~ ~~22~ air destroy

execute if block ~~23~ oak_log  run fill ~~23~ ~~23~ air destroy
execute if block ~~23~ spruce_log  run fill ~~23~ ~~23~ air destroy
execute if block ~~23~ cherry_log  run fill ~~23~ ~~23~ air destroy
execute if block ~~23~ jungle_log  run fill ~~23~ ~~23~ air destroy
execute if block ~~23~ birch_log  run fill ~~23~ ~~23~ air destroy
execute if block ~~23~ acacia_log  run fill ~~23~ ~~23~ air destroy
execute if block ~~23~ dark_oak_log  run fill ~~23~ ~~23~ air destroy
execute if block ~~23~ mangrove_log  run fill ~~23~ ~~23~ air destroy
execute if block ~~23~ crimson_stem  run fill ~~23~ ~~23~ air destroy
execute if block ~~23~ warped_stem  run fill ~~23~ ~~23~ air destroy

execute if block ~~24~ oak_log  run fill ~~24~ ~~24~ air destroy
execute if block ~~24~ spruce_log  run fill ~~24~ ~~24~ air destroy
execute if block ~~24~ cherry_log  run fill ~~24~ ~~24~ air destroy
execute if block ~~24~ jungle_log  run fill ~~24~ ~~24~ air destroy
execute if block ~~24~ birch_log  run fill ~~24~ ~~24~ air destroy
execute if block ~~24~ acacia_log  run fill ~~24~ ~~24~ air destroy
execute if block ~~24~ dark_oak_log  run fill ~~24~ ~~24~ air destroy
execute if block ~~24~ mangrove_log  run fill ~~24~ ~~24~ air destroy
execute if block ~~24~ crimson_stem  run fill ~~24~ ~~24~ air destroy
execute if block ~~24~ warped_stem  run fill ~~24~ ~~24~ air destroy

execute if block ~~25~ oak_log  run fill ~~25~ ~~25~ air destroy
execute if block ~~25~ spruce_log  run fill ~~25~ ~~25~ air destroy
execute if block ~~25~ cherry_log  run fill ~~25~ ~~25~ air destroy
execute if block ~~25~ jungle_log  run fill ~~25~ ~~25~ air destroy
execute if block ~~25~ birch_log  run fill ~~25~ ~~25~ air destroy
execute if block ~~25~ acacia_log  run fill ~~25~ ~~25~ air destroy
execute if block ~~25~ dark_oak_log  run fill ~~25~ ~~25~ air destroy
execute if block ~~25~ mangrove_log  run fill ~~25~ ~~25~ air destroy
execute if block ~~25~ crimson_stem  run fill ~~25~ ~~25~ air destroy
execute if block ~~25~ warped_stem  run fill ~~25~ ~~25~ air destroy

execute if block ~~26~ oak_log  run fill ~~26~ ~~26~ air destroy
execute if block ~~26~ spruce_log  run fill ~~26~ ~~26~ air destroy
execute if block ~~26~ cherry_log  run fill ~~26~ ~~26~ air destroy
execute if block ~~26~ jungle_log  run fill ~~26~ ~~26~ air destroy
execute if block ~~26~ birch_log  run fill ~~26~ ~~26~ air destroy
execute if block ~~26~ acacia_log  run fill ~~26~ ~~26~ air destroy
execute if block ~~26~ dark_oak_log  run fill ~~26~ ~~26~ air destroy
execute if block ~~26~ mangrove_log  run fill ~~26~ ~~26~ air destroy
execute if block ~~26~ crimson_stem  run fill ~~26~ ~~26~ air destroy
execute if block ~~26~ warped_stem  run fill ~~26~ ~~26~ air destroy

execute if block ~~27~ oak_log  run fill ~~27~ ~~27~ air destroy
execute if block ~~27~ spruce_log  run fill ~~27~ ~~27~ air destroy
execute if block ~~27~ cherry_log  run fill ~~27~ ~~27~ air destroy
execute if block ~~27~ jungle_log  run fill ~~27~ ~~27~ air destroy
execute if block ~~27~ birch_log  run fill ~~27~ ~~27~ air destroy
execute if block ~~27~ acacia_log  run fill ~~27~ ~~27~ air destroy
execute if block ~~27~ dark_oak_log  run fill ~~27~ ~~27~ air destroy
execute if block ~~27~ mangrove_log  run fill ~~27~ ~~27~ air destroy
execute if block ~~27~ crimson_stem  run fill ~~27~ ~~27~ air destroy
execute if block ~~27~ warped_stem  run fill ~~27~ ~~27~ air destroy

execute if block ~~28~ oak_log  run fill ~~28~ ~~28~ air destroy
execute if block ~~28~ spruce_log  run fill ~~28~ ~~28~ air destroy
execute if block ~~28~ cherry_log  run fill ~~28~ ~~28~ air destroy
execute if block ~~28~ jungle_log  run fill ~~28~ ~~28~ air destroy
execute if block ~~28~ birch_log  run fill ~~28~ ~~28~ air destroy
execute if block ~~28~ acacia_log  run fill ~~28~ ~~28~ air destroy
execute if block ~~28~ dark_oak_log  run fill ~~28~ ~~28~ air destroy
execute if block ~~28~ mangrove_log  run fill ~~28~ ~~28~ air destroy
execute if block ~~28~ crimson_stem  run fill ~~28~ ~~28~ air destroy
execute if block ~~28~ warped_stem  run fill ~~28~ ~~28~ air destroy

execute if block ~~29~ oak_log  run fill ~~29~ ~~29~ air destroy
execute if block ~~29~ spruce_log  run fill ~~29~ ~~29~ air destroy
execute if block ~~29~ cherry_log  run fill ~~29~ ~~29~ air destroy
execute if block ~~29~ jungle_log  run fill ~~29~ ~~29~ air destroy
execute if block ~~29~ birch_log  run fill ~~29~ ~~29~ air destroy
execute if block ~~29~ acacia_log  run fill ~~29~ ~~29~ air destroy
execute if block ~~29~ dark_oak_log  run fill ~~29~ ~~29~ air destroy
execute if block ~~29~ mangrove_log  run fill ~~29~ ~~29~ air destroy
execute if block ~~29~ crimson_stem  run fill ~~29~ ~~29~ air destroy
execute if block ~~29~ warped_stem  run fill ~~29~ ~~29~ air destroy

execute if block ~~30~ oak_log  run fill ~~30~ ~~30~ air destroy
execute if block ~~30~ spruce_log  run fill ~~30~ ~~30~ air destroy
execute if block ~~30~ cherry_log  run fill ~~30~ ~~30~ air destroy
execute if block ~~30~ jungle_log  run fill ~~30~ ~~30~ air destroy
execute if block ~~30~ birch_log  run fill ~~30~ ~~30~ air destroy
execute if block ~~30~ acacia_log  run fill ~~30~ ~~30~ air destroy
execute if block ~~30~ dark_oak_log  run fill ~~30~ ~~30~ air destroy
execute if block ~~30~ mangrove_log  run fill ~~30~ ~~30~ air destroy
execute if block ~~30~ crimson_stem  run fill ~~30~ ~~30~ air destroy
execute if block ~~30~ warped_stem  run fill ~~30~ ~~30~ air destroy