particle edx:yellow_spore_particles ~~-1~
particle edx:yellow_spore_particles ~~-1~
particle edx:yellow_spore_particles ~~-1~
particle edx:yellow_spore_particles ~~-1~
particle edx:yellow_spore_particles ~~-1~
particle edx:yellow_spore_particles ~~-1~
particle edx:yellow_spore_particles ~~-1~
particle edx:yellow_spore_particles ~~-1~
particle edx:yellow_spore_particles ~~-1~
particle edx:yellow_spore_particles ~~-1~