setblock ~1 ~0 ~ xp:abyssal_fungus
setblock ~2 ~0 ~ xp:abyssal_fungus_bottom
setblock ~3 ~0 ~ xp:abyssal_fungus_top
setblock ~4 ~0 ~ xp:abyssal_vein
setblock ~5 ~0 ~ xp:abyssal_void_roots
setblock ~6 ~0 ~ xp:abyss_grass
setblock ~7 ~0 ~ xp:abyss_grass_bushy
setblock ~8 ~0 ~ xp:abyss_grass_bushy_1
setblock ~9 ~0 ~ xp:abyss_grass_full
setblock ~10 ~0 ~ xp:abyss_grass_plant
setblock ~11 ~0 ~ xp:abyss_grass_thick_roots
setblock ~12 ~0 ~ xp:abyss_rooted
setblock ~13 ~0 ~ xp:abyss_rooted_grass
setblock ~14 ~0 ~ xp:abyss_rooted_grass_bushy
setblock ~15 ~0 ~ xp:ender_poppy
setblock ~16 ~0 ~ xp:voiding_larp
setblock ~17 ~0 ~ xp:voiding_larp_fan
setblock ~18 ~0 ~ xp:voiding_poppy
setblock ~19 ~0 ~ xp:void_flower
setblock ~0 ~1 ~ xp:void_ploom
setblock ~1 ~1 ~ xp:blunum_cluster
setblock ~2 ~1 ~ xp:blunum_crystal
setblock ~3 ~1 ~ xp:blunum_crystallite
setblock ~4 ~1 ~ xp:blunum_crystal_cluster
setblock ~5 ~1 ~ xp:blunum_crystal_cluster_small
setblock ~6 ~1 ~ xp:blunum_magnum_crystallite
setblock ~7 ~1 ~ xp:bulb_blossom
setblock ~8 ~1 ~ xp:chorus_flower_top
setblock ~9 ~1 ~ xp:hardened_root
setblock ~10 ~1 ~ xp:lantern_lily
setblock ~11 ~1 ~ xp:lantern_lily_bottom
setblock ~12 ~1 ~ xp:lantern_lily_sprout
setblock ~13 ~1 ~ xp:lantern_lily_top
setblock ~14 ~1 ~ xp:magnum_cluster
setblock ~15 ~1 ~ xp:magnum_crystal
setblock ~16 ~1 ~ xp:magnum_crystal_cluster
setblock ~17 ~1 ~ xp:magnum_crystal_cluster_small
setblock ~18 ~1 ~ xp:riftland_fortified_block
setblock ~19 ~1 ~ xp:riftland_void_block
setblock ~0 ~2 ~ xp:riftstone_strip
setblock ~1 ~2 ~ xp:rooted_echoing_vines_bottom
setblock ~2 ~2 ~ xp:rooted_echoing_vines_top
setblock ~3 ~2 ~ xp:tendril_blossom
setblock ~4 ~2 ~ xp:dark_purpur_bricks
setblock ~5 ~2 ~ xp:dark_purpur_bricks_cracked
setblock ~6 ~2 ~ xp:dark_purpur_bricks_echoing
setblock ~7 ~2 ~ xp:dark_purpur_bricks_wilds
setblock ~8 ~2 ~ xp:dark_purpur_chiseled
setblock ~9 ~2 ~ xp:dark_purpur_chiseled_cracked
setblock ~10 ~2 ~ xp:dark_purpur_fortified
setblock ~11 ~2 ~ xp:dark_purpur_fortified_chiseled
setblock ~12 ~2 ~ xp:dark_purpur_fortified_cracked
setblock ~13 ~2 ~ xp:dark_purpur_fortified_echoing
setblock ~14 ~2 ~ xp:dark_purpur_fortified_polished
setblock ~15 ~2 ~ xp:dark_purpur_fortified_wilds
setblock ~16 ~2 ~ xp:dark_purpur_headstone
setblock ~17 ~2 ~ xp:dark_purpur_headstone_cracked
setblock ~18 ~2 ~ xp:dark_purpur_lantern
setblock ~19 ~2 ~ xp:dark_purpur_pillar
setblock ~0 ~3 ~ xp:dark_purpur_pillar_cracked
setblock ~1 ~3 ~ xp:dark_purpur_polished
setblock ~2 ~3 ~ xp:dark_purpur_polished_cracked
setblock ~3 ~3 ~ xp:gargoyle
setblock ~4 ~3 ~ xp:gargoyle_1
setblock ~5 ~3 ~ xp:gargoyle_2
setblock ~6 ~3 ~ xp:gargoyle_3
setblock ~7 ~3 ~ xp:echoing_flower_fig
setblock ~8 ~3 ~ xp:echoing_flower_fig_plant
setblock ~9 ~3 ~ xp:echoing_grass
setblock ~10 ~3 ~ xp:echoing_grass_bushy
setblock ~11 ~3 ~ xp:echoing_grass_bushy_full
setblock ~12 ~3 ~ xp:echoing_grass_full
setblock ~13 ~3 ~ xp:echoing_grass_plant
setblock ~14 ~3 ~ xp:echoing_rooted_grass
setblock ~15 ~3 ~ xp:echoing_vines
setblock ~16 ~3 ~ xp:sparse_echoing_grass
setblock ~17 ~3 ~ xp:ender_bricks
setblock ~18 ~3 ~ xp:ender_bricks_chiseled
setblock ~19 ~3 ~ xp:ender_bricks_cracked
setblock ~0 ~4 ~ xp:ender_bricks_heavy
setblock ~1 ~4 ~ xp:ender_eye_block
setblock ~2 ~4 ~ xp:ender_eye_lit_block
setblock ~3 ~4 ~ xp:end_bricks_mossy
setblock ~4 ~4 ~ xp:eye_of_ender_block
setblock ~5 ~4 ~ xp:gateway_block
setblock ~6 ~4 ~ xp:purpur_cracked
setblock ~7 ~4 ~ xp:end_stone_chiseled
setblock ~8 ~4 ~ xp:end_stone_cluster
setblock ~9 ~4 ~ xp:end_stone_crushed
setblock ~10 ~4 ~ xp:end_stone_headstone
setblock ~11 ~4 ~ xp:end_stone_heavy
setblock ~12 ~4 ~ xp:end_stone_pillar
setblock ~13 ~4 ~ xp:end_stone_sap
setblock ~14 ~4 ~ xp:end_stone_sediment
setblock ~15 ~4 ~ xp:end_stone_sediment_slim
setblock ~16 ~4 ~ xp:end_stone_sediment_thick
setblock ~17 ~4 ~ xp:end_stone_tiles
setblock ~18 ~4 ~ xp:abyss_leaves
setblock ~19 ~4 ~ xp:echoing_mite_leaves
setblock ~0 ~5 ~ xp:echoing_leaves
setblock ~1 ~5 ~ xp:echoing_pome_leaves
setblock ~2 ~5 ~ xp:echoing_pome_thick_leaves
setblock ~3 ~5 ~ xp:echoing_thick_leaves
setblock ~4 ~5 ~ xp:echoing_thick_mite_leaves
setblock ~5 ~5 ~ xp:enderfig_leaves
setblock ~6 ~5 ~ xp:enderfig_thick_leaves
setblock ~7 ~5 ~ xp:wilds_flower_thick_leaves
setblock ~8 ~5 ~ xp:wilds_leaves
setblock ~9 ~5 ~ xp:wilds_thick_leaves
setblock ~10 ~5 ~ xp:bedrock_pillar
setblock ~11 ~5 ~ xp:chorus_plant_block
setblock ~12 ~5 ~ xp:enderite_crystalized
setblock ~13 ~5 ~ xp:ender_beam
setblock ~14 ~5 ~ xp:ender_goo
setblock ~15 ~5 ~ xp:ender_rune
setblock ~16 ~5 ~ xp:endstrip
setblock ~17 ~5 ~ xp:end_glass
setblock ~18 ~5 ~ xp:end_lantern
setblock ~19 ~5 ~ xp:end_lantern_fortified
setblock ~0 ~6 ~ xp:end_lantern_fortified_chiseled
setblock ~1 ~6 ~ xp:end_obsidian
setblock ~2 ~6 ~ xp:end_obsidian_polished
setblock ~3 ~6 ~ xp:magnum_crystallite
setblock ~4 ~6 ~ xp:enderite_ore
setblock ~5 ~6 ~ xp:end_stone_diamond_ore
setblock ~6 ~6 ~ xp:end_stone_iron_ore
setblock ~7 ~6 ~ xp:end_stone_lapis_ore
setblock ~8 ~6 ~ xp:riftstone_diamond_ore
setblock ~9 ~6 ~ xp:enderite_ore_riftstone
setblock ~10 ~6 ~ xp:void_crystal_ore_riftstone
setblock ~11 ~6 ~ xp:void_crystal_ore
setblock ~12 ~6 ~ xp:wall_torch_block
setblock ~13 ~6 ~ xp:wall_torch_block_1
setblock ~14 ~6 ~ xp:wall_torch_block_2
setblock ~15 ~6 ~ xp:wall_torch_block_3
setblock ~16 ~6 ~ xp:sparse_wilds_grass
setblock ~17 ~6 ~ xp:wilds_flower
setblock ~18 ~6 ~ xp:wilds_grass
setblock ~19 ~6 ~ xp:wilds_grass_bushy
setblock ~0 ~7 ~ xp:wilds_grass_plant
setblock ~1 ~7 ~ xp:wilds_sediment_grass
setblock ~2 ~7 ~ xp:wilds_tallgrass
setblock ~3 ~7 ~ xp:wilds_tallgrass_top
setblock ~4 ~7 ~ xp:small_wild_chorus_block
setblock ~5 ~7 ~ xp:abyssal_log
setblock ~6 ~7 ~ xp:abyssal_log_full
setblock ~7 ~7 ~ xp:abyssal_log_roots
setblock ~8 ~7 ~ xp:abyssal_planks
setblock ~9 ~7 ~ xp:echoing_log
setblock ~10 ~7 ~ xp:echoing_log_full
setblock ~11 ~7 ~ xp:echoing_planks
setblock ~12 ~7 ~ xp:echoing_root_log
setblock ~13 ~7 ~ xp:wilds_log
setblock ~14 ~7 ~ xp:wilds_log_full
setblock ~15 ~7 ~ xp:wilds_planks
setblock ~16 ~7 ~ xp:wilds_vein_log