# initialize values
scoreboard players set @s achievements1 0
scoreboard players set @s achievements2 0
scoreboard players set @s achievements3 0
scoreboard players set @s achievements4 0
scoreboard players set @s achievements5 0
scoreboard players set @s achievements6 0
scoreboard players set @s achievements7 0
scoreboard players set @s achievements8 0
scoreboard players set @s achievements9 0
scoreboard players set @s achievements10 0
scoreboard players set @s achievements11 0
scoreboard players set @s achievements12 0
scoreboard players set @s achievements13 0
scoreboard players set @s achievements14 0
scoreboard players set @s achievements15 0
scoreboard players set @s achievements16 0
scoreboard players set @s achievements17 0
scoreboard players set @s achievements18 0
scoreboard players set @s achievements19 0
scoreboard players set @s achievements20 0