execute as @s[scores={striker_thrown=1}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 1
execute as @s[scores={striker_thrown=2}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 2
execute as @s[scores={striker_thrown=3}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 3
execute as @s[scores={striker_thrown=4}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 4
execute as @s[scores={striker_thrown=5}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 5
execute as @s[scores={striker_thrown=6}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 6
execute as @s[scores={striker_thrown=7}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 7
execute as @s[scores={striker_thrown=8}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 8
execute as @s[scores={striker_thrown=9}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 9
execute as @s[scores={striker_thrown=10}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 10
execute as @s[scores={striker_thrown=11}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 11
execute as @s[scores={striker_thrown=12}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 12
execute as @s[scores={striker_thrown=13}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 13
execute as @s[scores={striker_thrown=14}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 14
execute as @s[scores={striker_thrown=15}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 15
execute as @s[scores={striker_thrown=16}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 16
execute as @s[scores={striker_thrown=17}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 17
execute as @s[scores={striker_thrown=18}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 18
execute as @s[scores={striker_thrown=19}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 19
execute as @s[scores={striker_thrown=20}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 20
execute as @s[scores={striker_thrown=21}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 21
execute as @s[scores={striker_thrown=22}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 22
execute as @s[scores={striker_thrown=23}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 23
execute as @s[scores={striker_thrown=24}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 24
execute as @s[scores={striker_thrown=25}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 25
execute as @s[scores={striker_thrown=26}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 26
execute as @s[scores={striker_thrown=27}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 27
execute as @s[scores={striker_thrown=28}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 28
execute as @s[scores={striker_thrown=29}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 29
execute as @s[scores={striker_thrown=30}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 30
execute as @s[scores={striker_thrown=31}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 31
execute as @s[scores={striker_thrown=32}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 32
execute as @s[scores={striker_thrown=33}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 33
execute as @s[scores={striker_thrown=34}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 34
execute as @s[scores={striker_thrown=35}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 35
execute as @s[scores={striker_thrown=36}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 36
execute as @s[scores={striker_thrown=37}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 37
execute as @s[scores={striker_thrown=38}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 38
execute as @s[scores={striker_thrown=39}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 39
execute as @s[scores={striker_thrown=40}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 40
execute as @s[scores={striker_thrown=41}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 41
execute as @s[scores={striker_thrown=42}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 42
execute as @s[scores={striker_thrown=43}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 43
execute as @s[scores={striker_thrown=44}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 44
execute as @s[scores={striker_thrown=45}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 45
execute as @s[scores={striker_thrown=46}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 46
execute as @s[scores={striker_thrown=47}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 47
execute as @s[scores={striker_thrown=48}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 48
execute as @s[scores={striker_thrown=49}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 49
execute as @s[scores={striker_thrown=50}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 50
execute as @s[scores={striker_thrown=51}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 51
execute as @s[scores={striker_thrown=52}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 52
execute as @s[scores={striker_thrown=53}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 53
execute as @s[scores={striker_thrown=54}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 54
execute as @s[scores={striker_thrown=55}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 55
execute as @s[scores={striker_thrown=56}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 56
execute as @s[scores={striker_thrown=57}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 57
execute as @s[scores={striker_thrown=58}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 58
execute as @s[scores={striker_thrown=59}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 59
execute as @s[scores={striker_thrown=60}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 60
execute as @s[scores={striker_thrown=61}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 61
execute as @s[scores={striker_thrown=62}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 62
execute as @s[scores={striker_thrown=63}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 63
execute as @s[scores={striker_thrown=64}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 64
execute as @s[scores={striker_thrown=65}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 65
execute as @s[scores={striker_thrown=66}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 66
execute as @s[scores={striker_thrown=67}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 67
execute as @s[scores={striker_thrown=68}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 68
execute as @s[scores={striker_thrown=69}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 69
execute as @s[scores={striker_thrown=70}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 70
execute as @s[scores={striker_thrown=71}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 71
execute as @s[scores={striker_thrown=72}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 72
execute as @s[scores={striker_thrown=73}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 73
execute as @s[scores={striker_thrown=74}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 74
execute as @s[scores={striker_thrown=75}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 75
execute as @s[scores={striker_thrown=76}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 76
execute as @s[scores={striker_thrown=77}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 77
execute as @s[scores={striker_thrown=78}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 78
execute as @s[scores={striker_thrown=79}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 79
execute as @s[scores={striker_thrown=80}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 80
execute as @s[scores={striker_thrown=81}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 81
execute as @s[scores={striker_thrown=82}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 82
execute as @s[scores={striker_thrown=83}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 83
execute as @s[scores={striker_thrown=84}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 84
execute as @s[scores={striker_thrown=85}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 85
execute as @s[scores={striker_thrown=86}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 86
execute as @s[scores={striker_thrown=87}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 87
execute as @s[scores={striker_thrown=88}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 88
execute as @s[scores={striker_thrown=89}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 89
execute as @s[scores={striker_thrown=90}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 90
execute as @s[scores={striker_thrown=91}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 91
execute as @s[scores={striker_thrown=92}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 92
execute as @s[scores={striker_thrown=93}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 93
execute as @s[scores={striker_thrown=94}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 94
execute as @s[scores={striker_thrown=95}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 95
execute as @s[scores={striker_thrown=96}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 96
execute as @s[scores={striker_thrown=97}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 97
execute as @s[scores={striker_thrown=98}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 98
execute as @s[scores={striker_thrown=99}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 99
execute as @s[scores={striker_thrown=100}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 100
execute as @s[scores={striker_thrown=101}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 101
execute as @s[scores={striker_thrown=102}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 102
execute as @s[scores={striker_thrown=103}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 103
execute as @s[scores={striker_thrown=104}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 104
execute as @s[scores={striker_thrown=105}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 105
execute as @s[scores={striker_thrown=106}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 106
execute as @s[scores={striker_thrown=107}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 107
execute as @s[scores={striker_thrown=108}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 108
execute as @s[scores={striker_thrown=109}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 109
execute as @s[scores={striker_thrown=110}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 110
execute as @s[scores={striker_thrown=111}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 111
execute as @s[scores={striker_thrown=112}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 112
execute as @s[scores={striker_thrown=113}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 113
execute as @s[scores={striker_thrown=114}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 114
execute as @s[scores={striker_thrown=115}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 115
execute as @s[scores={striker_thrown=116}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 116
execute as @s[scores={striker_thrown=117}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 117
execute as @s[scores={striker_thrown=118}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 118
execute as @s[scores={striker_thrown=119}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 119
execute as @s[scores={striker_thrown=120}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 120
execute as @s[scores={striker_thrown=121}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 121
execute as @s[scores={striker_thrown=122}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 122
execute as @s[scores={striker_thrown=123}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 123
execute as @s[scores={striker_thrown=124}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 124
execute as @s[scores={striker_thrown=125}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 125
execute as @s[scores={striker_thrown=126}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 126
execute as @s[scores={striker_thrown=127}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 127
execute as @s[scores={striker_thrown=128}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 128
execute as @s[scores={striker_thrown=129}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 129
execute as @s[scores={striker_thrown=130}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 130
execute as @s[scores={striker_thrown=131}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 131
execute as @s[scores={striker_thrown=132}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 132
execute as @s[scores={striker_thrown=133}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 133
execute as @s[scores={striker_thrown=134}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 134
execute as @s[scores={striker_thrown=135}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 135
execute as @s[scores={striker_thrown=136}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 136
execute as @s[scores={striker_thrown=137}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 137
execute as @s[scores={striker_thrown=138}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 138
execute as @s[scores={striker_thrown=139}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 139
execute as @s[scores={striker_thrown=140}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 140
execute as @s[scores={striker_thrown=141}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 141
execute as @s[scores={striker_thrown=142}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 142
execute as @s[scores={striker_thrown=143}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 143
execute as @s[scores={striker_thrown=144}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 144
execute as @s[scores={striker_thrown=145}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 145
execute as @s[scores={striker_thrown=146}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 146
execute as @s[scores={striker_thrown=147}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 147
execute as @s[scores={striker_thrown=148}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 148
execute as @s[scores={striker_thrown=149}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 149
execute as @s[scores={striker_thrown=150}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 150
execute as @s[scores={striker_thrown=151}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 151
execute as @s[scores={striker_thrown=152}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 152
execute as @s[scores={striker_thrown=153}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 153
execute as @s[scores={striker_thrown=154}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 154
execute as @s[scores={striker_thrown=155}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 155
execute as @s[scores={striker_thrown=156}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 156
execute as @s[scores={striker_thrown=157}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 157
execute as @s[scores={striker_thrown=158}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 158
execute as @s[scores={striker_thrown=159}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 159
execute as @s[scores={striker_thrown=160}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 160
execute as @s[scores={striker_thrown=161}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 161
execute as @s[scores={striker_thrown=162}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 162
execute as @s[scores={striker_thrown=163}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 163
execute as @s[scores={striker_thrown=164}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 164
execute as @s[scores={striker_thrown=165}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 165
execute as @s[scores={striker_thrown=166}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 166
execute as @s[scores={striker_thrown=167}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 167
execute as @s[scores={striker_thrown=168}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 168
execute as @s[scores={striker_thrown=169}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 169
execute as @s[scores={striker_thrown=170}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 170
execute as @s[scores={striker_thrown=171}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 171
execute as @s[scores={striker_thrown=172}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 172
execute as @s[scores={striker_thrown=173}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 173
execute as @s[scores={striker_thrown=174}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 174
execute as @s[scores={striker_thrown=175}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 175
execute as @s[scores={striker_thrown=176}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 176
execute as @s[scores={striker_thrown=177}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 177
execute as @s[scores={striker_thrown=178}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 178
execute as @s[scores={striker_thrown=179}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 179
execute as @s[scores={striker_thrown=180}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 180
execute as @s[scores={striker_thrown=181}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 181
execute as @s[scores={striker_thrown=182}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 182
execute as @s[scores={striker_thrown=183}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 183
execute as @s[scores={striker_thrown=184}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 184
execute as @s[scores={striker_thrown=185}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 185
execute as @s[scores={striker_thrown=186}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 186
execute as @s[scores={striker_thrown=187}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 187
execute as @s[scores={striker_thrown=188}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 188
execute as @s[scores={striker_thrown=189}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 189
execute as @s[scores={striker_thrown=190}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 190
execute as @s[scores={striker_thrown=191}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 191
execute as @s[scores={striker_thrown=192}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 192
execute as @s[scores={striker_thrown=193}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 193
execute as @s[scores={striker_thrown=194}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 194
execute as @s[scores={striker_thrown=195}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 195
execute as @s[scores={striker_thrown=196}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 196
execute as @s[scores={striker_thrown=197}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 197
execute as @s[scores={striker_thrown=198}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 198
execute as @s[scores={striker_thrown=199}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 199
execute as @s[scores={striker_thrown=200}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 200
execute as @s[scores={striker_thrown=201}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 201
execute as @s[scores={striker_thrown=202}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 202
execute as @s[scores={striker_thrown=203}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 203
execute as @s[scores={striker_thrown=204}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 204
execute as @s[scores={striker_thrown=205}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 205
execute as @s[scores={striker_thrown=206}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 206
execute as @s[scores={striker_thrown=207}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 207
execute as @s[scores={striker_thrown=208}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 208
execute as @s[scores={striker_thrown=209}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 209
execute as @s[scores={striker_thrown=210}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 210
execute as @s[scores={striker_thrown=211}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 211
execute as @s[scores={striker_thrown=212}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 212
execute as @s[scores={striker_thrown=213}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 213
execute as @s[scores={striker_thrown=214}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 214
execute as @s[scores={striker_thrown=215}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 215
execute as @s[scores={striker_thrown=216}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 216
execute as @s[scores={striker_thrown=217}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 217
execute as @s[scores={striker_thrown=218}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 218
execute as @s[scores={striker_thrown=219}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 219
execute as @s[scores={striker_thrown=220}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 220
execute as @s[scores={striker_thrown=221}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 221
execute as @s[scores={striker_thrown=222}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 222
execute as @s[scores={striker_thrown=223}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 223
execute as @s[scores={striker_thrown=224}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 224
execute as @s[scores={striker_thrown=225}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 225
execute as @s[scores={striker_thrown=226}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 226
execute as @s[scores={striker_thrown=227}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 227
execute as @s[scores={striker_thrown=228}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 228
execute as @s[scores={striker_thrown=229}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 229
execute as @s[scores={striker_thrown=230}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 230
execute as @s[scores={striker_thrown=231}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 231
execute as @s[scores={striker_thrown=232}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 232
execute as @s[scores={striker_thrown=233}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 233
execute as @s[scores={striker_thrown=234}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 234
execute as @s[scores={striker_thrown=235}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 235
execute as @s[scores={striker_thrown=236}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 236
execute as @s[scores={striker_thrown=237}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 237
execute as @s[scores={striker_thrown=238}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 238
execute as @s[scores={striker_thrown=239}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 239
execute as @s[scores={striker_thrown=240}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 240
execute as @s[scores={striker_thrown=241}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 241
execute as @s[scores={striker_thrown=242}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 242
execute as @s[scores={striker_thrown=243}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 243
execute as @s[scores={striker_thrown=244}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 244
execute as @s[scores={striker_thrown=245}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 245
execute as @s[scores={striker_thrown=246}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 246
execute as @s[scores={striker_thrown=247}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 247
execute as @s[scores={striker_thrown=248}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 248
execute as @s[scores={striker_thrown=249}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 249
execute as @s[scores={striker_thrown=250}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 250
execute as @s[scores={striker_thrown=251}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 251
execute as @s[scores={striker_thrown=252}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 252
execute as @s[scores={striker_thrown=253}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 253
execute as @s[scores={striker_thrown=254}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 254
execute as @s[scores={striker_thrown=255}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 255
execute as @s[scores={striker_thrown=256}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 256
execute as @s[scores={striker_thrown=257}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 257
execute as @s[scores={striker_thrown=258}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 258
execute as @s[scores={striker_thrown=259}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 259
execute as @s[scores={striker_thrown=260}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 260
execute as @s[scores={striker_thrown=261}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 261
execute as @s[scores={striker_thrown=262}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 262
execute as @s[scores={striker_thrown=263}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 263
execute as @s[scores={striker_thrown=264}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 264
execute as @s[scores={striker_thrown=265}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 265
execute as @s[scores={striker_thrown=266}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 266
execute as @s[scores={striker_thrown=267}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 267
execute as @s[scores={striker_thrown=268}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 268
execute as @s[scores={striker_thrown=269}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 269
execute as @s[scores={striker_thrown=270}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 270
execute as @s[scores={striker_thrown=271}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 271
execute as @s[scores={striker_thrown=272}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 272
execute as @s[scores={striker_thrown=273}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 273
execute as @s[scores={striker_thrown=274}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 274
execute as @s[scores={striker_thrown=275}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 275
execute as @s[scores={striker_thrown=276}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 276
execute as @s[scores={striker_thrown=277}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 277
execute as @s[scores={striker_thrown=278}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 278
execute as @s[scores={striker_thrown=279}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 279
execute as @s[scores={striker_thrown=280}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 280
execute as @s[scores={striker_thrown=281}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 281
execute as @s[scores={striker_thrown=282}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 282
execute as @s[scores={striker_thrown=283}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 283
execute as @s[scores={striker_thrown=284}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 284
execute as @s[scores={striker_thrown=285}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 285
execute as @s[scores={striker_thrown=286}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 286
execute as @s[scores={striker_thrown=287}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 287
execute as @s[scores={striker_thrown=288}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 288
execute as @s[scores={striker_thrown=289}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 289
execute as @s[scores={striker_thrown=290}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 290
execute as @s[scores={striker_thrown=291}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 291
execute as @s[scores={striker_thrown=292}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 292
execute as @s[scores={striker_thrown=293}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 293
execute as @s[scores={striker_thrown=294}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 294
execute as @s[scores={striker_thrown=295}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 295
execute as @s[scores={striker_thrown=296}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 296
execute as @s[scores={striker_thrown=297}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 297
execute as @s[scores={striker_thrown=298}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 298
execute as @s[scores={striker_thrown=299}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 299
execute as @s[scores={striker_thrown=300}] at @s run replaceitem entity @s slot.weapon.mainhand 0 xp:void_striker 1 300