# execute if entity @s[tag=upper_arm] run say upper_arm hit
# execute if entity @s[tag=lower_arm] run say lower_arm hit
# execute if entity @s[tag=body] run say body hit
# execute if entity @s[tag=head] run say head hit
scoreboard players set .2 math 2

# Head      = damage x 2
# Upper Arm = damage x 2
# Body      = damage x 1
# Lower Arm = damage x 0.5
execute if entity @s[tag=head] run scoreboard players operation endboss_damage endboss *= .2 math
execute if entity @s[tag=upper_arm] run scoreboard players operation endboss_damage endboss *= .2 math
execute if entity @s[tag=lower_arm] run scoreboard players operation endboss_damage endboss /= .2 math

title @a[r=50] title xp_ui.custom_bossbar.heart_of_ender_boss.hurt
event entity @e[type=xp:heart_of_ender_boss] xp:got_hurt

execute if score awaiting_last_hit endboss matches 1 run event entity @e[type=xp:heart_of_ender_boss] xp:stage_4

execute if score endboss_damage endboss matches 1 run damage @e[type=xp:heart_of_ender_boss] 1 contact entity @p
execute if score endboss_damage endboss matches 2 run damage @e[type=xp:heart_of_ender_boss] 2 contact entity @p
execute if score endboss_damage endboss matches 3 run damage @e[type=xp:heart_of_ender_boss] 3 contact entity @p
execute if score endboss_damage endboss matches 4 run damage @e[type=xp:heart_of_ender_boss] 4 contact entity @p
execute if score endboss_damage endboss matches 5 run damage @e[type=xp:heart_of_ender_boss] 5 contact entity @p
execute if score endboss_damage endboss matches 6 run damage @e[type=xp:heart_of_ender_boss] 6 contact entity @p
execute if score endboss_damage endboss matches 7 run damage @e[type=xp:heart_of_ender_boss] 7 contact entity @p
execute if score endboss_damage endboss matches 8 run damage @e[type=xp:heart_of_ender_boss] 8 contact entity @p
execute if score endboss_damage endboss matches 9 run damage @e[type=xp:heart_of_ender_boss] 9 contact entity @p
execute if score endboss_damage endboss matches 10 run damage @e[type=xp:heart_of_ender_boss] 10 contact entity @p
execute if score endboss_damage endboss matches 11 run damage @e[type=xp:heart_of_ender_boss] 11 contact entity @p
execute if score endboss_damage endboss matches 12 run damage @e[type=xp:heart_of_ender_boss] 12 contact entity @p
execute if score endboss_damage endboss matches 13 run damage @e[type=xp:heart_of_ender_boss] 13 contact entity @p
execute if score endboss_damage endboss matches 14 run damage @e[type=xp:heart_of_ender_boss] 14 contact entity @p
execute if score endboss_damage endboss matches 15 run damage @e[type=xp:heart_of_ender_boss] 15 contact entity @p
execute if score endboss_damage endboss matches 16 run damage @e[type=xp:heart_of_ender_boss] 16 contact entity @p
execute if score endboss_damage endboss matches 17 run damage @e[type=xp:heart_of_ender_boss] 17 contact entity @p
execute if score endboss_damage endboss matches 18 run damage @e[type=xp:heart_of_ender_boss] 18 contact entity @p
execute if score endboss_damage endboss matches 19 run damage @e[type=xp:heart_of_ender_boss] 19 contact entity @p
execute if score endboss_damage endboss matches 20 run damage @e[type=xp:heart_of_ender_boss] 20 contact entity @p
execute if score endboss_damage endboss matches 21 run damage @e[type=xp:heart_of_ender_boss] 21 contact entity @p
execute if score endboss_damage endboss matches 22 run damage @e[type=xp:heart_of_ender_boss] 22 contact entity @p
execute if score endboss_damage endboss matches 23 run damage @e[type=xp:heart_of_ender_boss] 23 contact entity @p
execute if score endboss_damage endboss matches 24 run damage @e[type=xp:heart_of_ender_boss] 24 contact entity @p
execute if score endboss_damage endboss matches 25 run damage @e[type=xp:heart_of_ender_boss] 25 contact entity @p
execute if score endboss_damage endboss matches 26 run damage @e[type=xp:heart_of_ender_boss] 26 contact entity @p
execute if score endboss_damage endboss matches 27 run damage @e[type=xp:heart_of_ender_boss] 27 contact entity @p
execute if score endboss_damage endboss matches 28 run damage @e[type=xp:heart_of_ender_boss] 28 contact entity @p
execute if score endboss_damage endboss matches 29 run damage @e[type=xp:heart_of_ender_boss] 29 contact entity @p
execute if score endboss_damage endboss matches 30 run damage @e[type=xp:heart_of_ender_boss] 30 contact entity @p
execute if score endboss_damage endboss matches 31 run damage @e[type=xp:heart_of_ender_boss] 31 contact entity @p
execute if score endboss_damage endboss matches 32 run damage @e[type=xp:heart_of_ender_boss] 32 contact entity @p
execute if score endboss_damage endboss matches 33 run damage @e[type=xp:heart_of_ender_boss] 33 contact entity @p
execute if score endboss_damage endboss matches 34 run damage @e[type=xp:heart_of_ender_boss] 34 contact entity @p
execute if score endboss_damage endboss matches 35 run damage @e[type=xp:heart_of_ender_boss] 35 contact entity @p
execute if score endboss_damage endboss matches 36 run damage @e[type=xp:heart_of_ender_boss] 36 contact entity @p
execute if score endboss_damage endboss matches 37 run damage @e[type=xp:heart_of_ender_boss] 37 contact entity @p
execute if score endboss_damage endboss matches 38 run damage @e[type=xp:heart_of_ender_boss] 38 contact entity @p
execute if score endboss_damage endboss matches 39 run damage @e[type=xp:heart_of_ender_boss] 39 contact entity @p
execute if score endboss_damage endboss matches 40 run damage @e[type=xp:heart_of_ender_boss] 40 contact entity @p
execute if score endboss_damage endboss matches 41 run damage @e[type=xp:heart_of_ender_boss] 41 contact entity @p
execute if score endboss_damage endboss matches 42 run damage @e[type=xp:heart_of_ender_boss] 42 contact entity @p
execute if score endboss_damage endboss matches 43 run damage @e[type=xp:heart_of_ender_boss] 43 contact entity @p
execute if score endboss_damage endboss matches 44 run damage @e[type=xp:heart_of_ender_boss] 44 contact entity @p
execute if score endboss_damage endboss matches 45 run damage @e[type=xp:heart_of_ender_boss] 45 contact entity @p
execute if score endboss_damage endboss matches 46 run damage @e[type=xp:heart_of_ender_boss] 46 contact entity @p
execute if score endboss_damage endboss matches 47 run damage @e[type=xp:heart_of_ender_boss] 47 contact entity @p
execute if score endboss_damage endboss matches 48 run damage @e[type=xp:heart_of_ender_boss] 48 contact entity @p
execute if score endboss_damage endboss matches 49 run damage @e[type=xp:heart_of_ender_boss] 49 contact entity @p
execute if score endboss_damage endboss matches 50 run damage @e[type=xp:heart_of_ender_boss] 50 contact entity @p
execute if score endboss_damage endboss matches 51 run damage @e[type=xp:heart_of_ender_boss] 51 contact entity @p
execute if score endboss_damage endboss matches 52 run damage @e[type=xp:heart_of_ender_boss] 52 contact entity @p
execute if score endboss_damage endboss matches 53 run damage @e[type=xp:heart_of_ender_boss] 53 contact entity @p
execute if score endboss_damage endboss matches 54 run damage @e[type=xp:heart_of_ender_boss] 54 contact entity @p
execute if score endboss_damage endboss matches 55 run damage @e[type=xp:heart_of_ender_boss] 55 contact entity @p
execute if score endboss_damage endboss matches 56 run damage @e[type=xp:heart_of_ender_boss] 56 contact entity @p
execute if score endboss_damage endboss matches 57 run damage @e[type=xp:heart_of_ender_boss] 57 contact entity @p
execute if score endboss_damage endboss matches 58 run damage @e[type=xp:heart_of_ender_boss] 58 contact entity @p
execute if score endboss_damage endboss matches 59 run damage @e[type=xp:heart_of_ender_boss] 59 contact entity @p
execute if score endboss_damage endboss matches 60 run damage @e[type=xp:heart_of_ender_boss] 60 contact entity @p
execute if score endboss_damage endboss matches 61 run damage @e[type=xp:heart_of_ender_boss] 61 contact entity @p
execute if score endboss_damage endboss matches 62 run damage @e[type=xp:heart_of_ender_boss] 62 contact entity @p
execute if score endboss_damage endboss matches 63 run damage @e[type=xp:heart_of_ender_boss] 63 contact entity @p
execute if score endboss_damage endboss matches 64 run damage @e[type=xp:heart_of_ender_boss] 64 contact entity @p
execute if score endboss_damage endboss matches 65 run damage @e[type=xp:heart_of_ender_boss] 65 contact entity @p
execute if score endboss_damage endboss matches 66 run damage @e[type=xp:heart_of_ender_boss] 66 contact entity @p
execute if score endboss_damage endboss matches 67 run damage @e[type=xp:heart_of_ender_boss] 67 contact entity @p
execute if score endboss_damage endboss matches 68 run damage @e[type=xp:heart_of_ender_boss] 68 contact entity @p
execute if score endboss_damage endboss matches 69 run damage @e[type=xp:heart_of_ender_boss] 69 contact entity @p
execute if score endboss_damage endboss matches 70 run damage @e[type=xp:heart_of_ender_boss] 70 contact entity @p
execute if score endboss_damage endboss matches 71 run damage @e[type=xp:heart_of_ender_boss] 71 contact entity @p
execute if score endboss_damage endboss matches 72 run damage @e[type=xp:heart_of_ender_boss] 72 contact entity @p
execute if score endboss_damage endboss matches 73 run damage @e[type=xp:heart_of_ender_boss] 73 contact entity @p
execute if score endboss_damage endboss matches 74 run damage @e[type=xp:heart_of_ender_boss] 74 contact entity @p
execute if score endboss_damage endboss matches 75 run damage @e[type=xp:heart_of_ender_boss] 75 contact entity @p
execute if score endboss_damage endboss matches 76 run damage @e[type=xp:heart_of_ender_boss] 76 contact entity @p
execute if score endboss_damage endboss matches 77 run damage @e[type=xp:heart_of_ender_boss] 77 contact entity @p
execute if score endboss_damage endboss matches 78 run damage @e[type=xp:heart_of_ender_boss] 78 contact entity @p
execute if score endboss_damage endboss matches 79 run damage @e[type=xp:heart_of_ender_boss] 79 contact entity @p
execute if score endboss_damage endboss matches 80 run damage @e[type=xp:heart_of_ender_boss] 80 contact entity @p
execute if score endboss_damage endboss matches 81 run damage @e[type=xp:heart_of_ender_boss] 81 contact entity @p
execute if score endboss_damage endboss matches 82 run damage @e[type=xp:heart_of_ender_boss] 82 contact entity @p
execute if score endboss_damage endboss matches 83 run damage @e[type=xp:heart_of_ender_boss] 83 contact entity @p
execute if score endboss_damage endboss matches 84 run damage @e[type=xp:heart_of_ender_boss] 84 contact entity @p
execute if score endboss_damage endboss matches 85 run damage @e[type=xp:heart_of_ender_boss] 85 contact entity @p
execute if score endboss_damage endboss matches 86 run damage @e[type=xp:heart_of_ender_boss] 86 contact entity @p
execute if score endboss_damage endboss matches 87 run damage @e[type=xp:heart_of_ender_boss] 87 contact entity @p
execute if score endboss_damage endboss matches 88 run damage @e[type=xp:heart_of_ender_boss] 88 contact entity @p
execute if score endboss_damage endboss matches 89 run damage @e[type=xp:heart_of_ender_boss] 89 contact entity @p
execute if score endboss_damage endboss matches 90 run damage @e[type=xp:heart_of_ender_boss] 90 contact entity @p
execute if score endboss_damage endboss matches 91 run damage @e[type=xp:heart_of_ender_boss] 91 contact entity @p
execute if score endboss_damage endboss matches 92 run damage @e[type=xp:heart_of_ender_boss] 92 contact entity @p
execute if score endboss_damage endboss matches 93 run damage @e[type=xp:heart_of_ender_boss] 93 contact entity @p
execute if score endboss_damage endboss matches 94 run damage @e[type=xp:heart_of_ender_boss] 94 contact entity @p
execute if score endboss_damage endboss matches 95 run damage @e[type=xp:heart_of_ender_boss] 95 contact entity @p
execute if score endboss_damage endboss matches 96 run damage @e[type=xp:heart_of_ender_boss] 96 contact entity @p
execute if score endboss_damage endboss matches 97 run damage @e[type=xp:heart_of_ender_boss] 97 contact entity @p
execute if score endboss_damage endboss matches 98 run damage @e[type=xp:heart_of_ender_boss] 98 contact entity @p
execute if score endboss_damage endboss matches 99 run damage @e[type=xp:heart_of_ender_boss] 99 contact entity @p
execute if score endboss_damage endboss matches 100.. run damage @e[type=xp:heart_of_ender_boss] 100 contact entity @p

scoreboard players set endboss_damage endboss 0