export default {
    forest: 1,
    desert: 2,
    jungle: 3,
    beach: 4,
    ocean: 5,
    mesa: 6,
    taiga: 7,
    frozen: 8,
    extreme_hills: 9,
    mountains: 10,
    plains: 11,
    savanna: 12,
    river: 13,
    swamp: 14,
    mangroves: 15,
    meadow: 16,
    mushroom: 17,
    birch: 18,
    dark_oak: 19,
};
//# sourceMappingURL=biomes.js.map